services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Loculus\SessionSecurityBundle\:
        resource: '../../../src/'
        exclude:
            - '../../../src/DependencyInjection/'

    Loculus\SessionSecurityBundle\EventListener\RequestListener:
        arguments:
            $validationManager: '@Loculus\SessionSecurityBundle\ValidationManager'
            $config: []
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', priority: 128 }
