services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Loculus\SessionSecurityBundle\:
        resource: '../../../src/'
        exclude:
            - '../../../src/DependencyInjection/'

    Loculus\SessionSecurityBundle\EventListener\RequestListener:
        arguments:
            $validationManager: '@Loculus\SessionSecurityBundle\ValidationManager'
            $config: []
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', priority: null }

    Loculus\SessionSecurityBundle\EventListener\InvalidSessionListener:
        arguments:
            $invalidationStrategyManager: '@Loculus\SessionSecurityBundle\InvalidationStrategyManager'
            $logger: '@Psr\Log\LoggerInterface'
            $config: []
        tags:
            - { name: 'kernel.event_listener', event: 'session_security.invalid_session', priority: null }
